### ISSUE TITLE
Api throwing exception

### ISSUE THREAD

**Issue by scrudden** [TheTransitClock/transitime#106]
This is being thrown if you look for routes in the API. It will most likely occur for all other calls. I think it is a jersey jar version issue.

![image](https://user-images.githubusercontent.com/6191822/45254947-a2963300-b378-11e8-9d8b-23d942df4e1a.png)

**Comment by scrudden** [comment]
@vsperez I think this relates to the swagger changes.

**Comment by vsperez** [comment]
Hi. If it is an issue with swagger, probably it is related to some dependency. Can you send me the resolved pom dependency list?. I have the api and swagger working on tc_issue_98, so I will check the dependency differences.

**Comment by scrudden** [comment]
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building transitclockApi 2.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ transitclockApi ---
[INFO] TheTransitClock:transitclockApi:war:2.0.0-SNAPSHOT
[INFO] +- javax.servlet:javax.servlet-api:jar:3.0.1:provided
[INFO] +- javax.ws.rs:javax.ws.rs-api:jar:2.0:compile
[INFO] +- org.glassfish.jersey.media:jersey-media-moxy:jar:2.24.1:compile
[INFO] |  +- org.glassfish.jersey.core:jersey-common:jar:2.24.1:compile
[INFO] |  |  +- javax.annotation:javax.annotation-api:jar:1.2:compile
[INFO] |  |  +- org.glassfish.hk2:hk2-api:jar:2.5.0-b05:compile
[INFO] |  |  |  +- org.glassfish.hk2:hk2-utils:jar:2.5.0-b05:compile
[INFO] |  |  |  \- org.glassfish.hk2.external:aopalliance-repackaged:jar:2.5.0-b05:compile
[INFO] |  |  +- org.glassfish.hk2.external:javax.inject:jar:2.5.0-b05:compile
[INFO] |  |  +- org.glassfish.hk2:hk2-locator:jar:2.5.0-b05:compile
[INFO] |  |  \- org.glassfish.hk2:osgi-resource-locator:jar:1.0.1:compile
[INFO] |  +- org.glassfish.jersey.ext:jersey-entity-filtering:jar:2.24.1:compile
[INFO] |  \- org.eclipse.persistence:org.eclipse.persistence.moxy:jar:2.6.0:compile
[INFO] |     +- org.eclipse.persistence:org.eclipse.persistence.core:jar:2.6.0:compile
[INFO] |     |  \- org.eclipse.persistence:org.eclipse.persistence.asm:jar:2.6.0:compile
[INFO] |     +- javax.validation:validation-api:jar:1.1.0.Final:compile
[INFO] |     \- org.glassfish:javax.json:jar:1.0.4:compile
[INFO] +- org.slf4j:slf4j-api:jar:1.7.2:compile
[INFO] +- org.glassfish.jersey.containers:jersey-container-servlet:jar:2.24.1:compile
[INFO] |  +- org.glassfish.jersey.containers:jersey-container-servlet-core:jar:2.24.1:compile
[INFO] |  \- org.glassfish.jersey.core:jersey-server:jar:2.24.1:compile
[INFO] |     +- org.glassfish.jersey.core:jersey-client:jar:2.24.1:compile
[INFO] |     \- org.glassfish.jersey.media:jersey-media-jaxb:jar:2.24.1:compile
[INFO] +- TheTransitClock:transitclockCore:jar:2.0.0-SNAPSHOT:compile
[INFO] |  +- com.esri.geometry:esri-geometry-api:jar:1.1:compile
[INFO] |  |  \- org.codehaus.jackson:jackson-core-asl:jar:1.9.12:compile
[INFO] |  +- com.simontuffs:one-jar-boot:jar:0.97.3:compile
[INFO] |  +- mysql:mysql-connector-java:jar:5.1.35:compile
[INFO] |  +- org.postgresql:postgresql:jar:9.3-1103-jdbc41:compile
[INFO] |  +- org.hibernate:hibernate-core:jar:4.3.9.Final:compile
[INFO] |  |  +- org.jboss.logging:jboss-logging:jar:3.1.3.GA:compile
[INFO] |  |  +- org.jboss.logging:jboss-logging-annotations:jar:1.2.0.Beta1:compile
[INFO] |  |  +- org.jboss.spec.javax.transaction:jboss-transaction-api_1.2_spec:jar:1.0.0.Final:compile
[INFO] |  |  +- dom4j:dom4j:jar:1.6.1:compile
[INFO] |  |  +- org.hibernate.javax.persistence:hibernate-jpa-2.1-api:jar:1.0.0.Final:compile
[INFO] |  |  +- antlr:antlr:jar:2.7.7:compile
[INFO] |  |  \- org.jboss:jandex:jar:1.1.0.Final:compile
[INFO] |  +- org.hibernate.common:hibernate-commons-annotations:jar:4.0.5.Final:compile
[INFO] |  +- org.hibernate:hibernate-c3p0:jar:4.3.9.Final:compile
[INFO] |  |  \- com.mchange:c3p0:jar:0.9.2.1:compile
[INFO] |  |     \- com.mchange:mchange-commons-java:jar:0.2.3.4:compile
[INFO] |  +- xml-apis:xml-apis:jar:1.4.01:compile
[INFO] |  +- ch.qos.logback:logback-core:jar:1.1.2:compile
[INFO] |  +- ch.qos.logback:logback-classic:jar:1.1.3:compile
[INFO] |  +- org.hsqldb:hsqldb:jar:2.2.4:compile
[INFO] |  +- org.apache.commons:commons-lang3:jar:3.3.2:compile
[INFO] |  +- org.jdom:jdom:jar:2.0.2:compile
[INFO] |  +- com.google.transit:gtfs-realtime-bindings:jar:0.0.4:compile
[INFO] |  |  \- com.google.protobuf:protobuf-java:jar:2.6.1:compile
[INFO] |  +- commons-cli:commons-cli:jar:1.2:compile
[INFO] |  +- org.hornetq:hornetq-core-client:jar:2.3.25.Final:compile
[INFO] |  |  +- org.jgroups:jgroups:jar:3.2.13.Final:compile
[INFO] |  |  +- org.hornetq:hornetq-commons:jar:2.3.25.Final:compile
[INFO] |  |  +- org.hornetq:hornetq-journal:jar:2.3.25.Final:compile
[INFO] |  |  \- io.netty:netty:jar:3.6.10.Final:compile
[INFO] |  +- org.hornetq:hornetq-jms-client:jar:2.3.25.Final:compile
[INFO] |  |  \- org.jboss.spec.javax.jms:jboss-jms-api_1.1_spec:jar:1.0.0.Final:compile
[INFO] |  +- org.java-websocket:Java-WebSocket:jar:1.3.0:compile
[INFO] |  +- org.json:json:jar:20140107:compile
[INFO] |  +- org.apache.commons:commons-csv:jar:1.1:compile
[INFO] |  +- net.jcip:jcip-annotations:jar:1.0:compile
[INFO] |  +- org.jasypt:jasypt:jar:1.9.2:compile
[INFO] |  +- javax.mail:mail:jar:1.4.7:compile
[INFO] |  |  \- javax.activation:activation:jar:1.1:compile
[INFO] |  +- commons-beanutils:commons-beanutils:jar:1.9.2:compile
[INFO] |  |  +- commons-logging:commons-logging:jar:1.1.1:compile
[INFO] |  |  \- commons-collections:commons-collections:jar:3.2.1:compile
[INFO] |  +- net.sf.ehcache:ehcache:jar:2.10.0:compile
[INFO] |  +- org.apache.commons:commons-jcs-core:jar:2.2:compile
[INFO] |  \- com.github.haifengl:smile-core:jar:1.5.1:compile
[INFO] |     +- com.github.haifengl:smile-data:jar:1.5.1:compile
[INFO] |     +- com.github.haifengl:smile-math:jar:1.5.1:compile
[INFO] |     \- com.github.haifengl:smile-graph:jar:1.5.1:compile
[INFO] +- com.google.guava:guava:jar:20.0:compile
[INFO] +- org.glassfish.jersey.bundles.repackaged:jersey-guava:jar:2.6:compile
[INFO] +- io.swagger.core.v3:swagger-jaxrs2:jar:2.0.2:compile
[INFO] |  +- com.fasterxml.jackson.core:jackson-databind:jar:2.9.5:compile
[INFO] |  |  +- com.fasterxml.jackson.core:jackson-annotations:jar:2.9.0:compile
[INFO] |  |  \- com.fasterxml.jackson.core:jackson-core:jar:2.9.5:compile
[INFO] |  +- org.reflections:reflections:jar:0.9.11:compile
[INFO] |  +- org.javassist:javassist:jar:3.22.0-GA:compile
[INFO] |  +- io.swagger.core.v3:swagger-models:jar:2.0.2:compile
[INFO] |  +- io.swagger.core.v3:swagger-annotations:jar:2.0.2:compile
[INFO] |  +- io.swagger.core.v3:swagger-integration:jar:2.0.2:compile
[INFO] |  |  \- io.swagger.core.v3:swagger-core:jar:2.0.2:compile
[INFO] |  |     +- javax.xml.bind:jaxb-api:jar:2.3.0:compile
[INFO] |  |     \- com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:jar:2.9.5:compile
[INFO] |  |        \- org.yaml:snakeyaml:jar:1.18:compile
[INFO] |  \- com.fasterxml.jackson.jaxrs:jackson-jaxrs-json-provider:jar:2.9.5:compile
[INFO] |     +- com.fasterxml.jackson.jaxrs:jackson-jaxrs-base:jar:2.9.5:compile
[INFO] |     \- com.fasterxml.jackson.module:jackson-module-jaxb-annotations:jar:2.9.5:compile
[INFO] \- org.webjars:swagger-ui:jar:3.17.1:compile
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.588 s
[INFO] Finished at: 2018-09-08T18:07:19+01:00
[INFO] Final Memory: 17M/217M
[INFO] ------------------------------------------------------------------------

**Comment by scrudden** [comment]
@vsperez See above for list of dependencies. Thanks, Sean.

**Comment by scrudden** [comment]
Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building transitclockApi 2.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-dependency-plugin:2.8:resolve (default-cli) @ transitclockApi ---
[INFO] 
[INFO] The following files have been resolved:
[INFO]    net.jcip:jcip-annotations:jar:1.0:compile
[INFO]    com.fasterxml.jackson.core:jackson-core:jar:2.9.5:compile
[INFO]    net.sf.ehcache:ehcache:jar:2.10.0:compile
[INFO]    com.mchange:mchange-commons-java:jar:0.2.3.4:compile
[INFO]    com.github.haifengl:smile-data:jar:1.5.1:compile
[INFO]    com.github.haifengl:smile-core:jar:1.5.1:compile
[INFO]    org.glassfish.jersey.core:jersey-client:jar:2.24.1:compile
[INFO]    org.hornetq:hornetq-journal:jar:2.3.25.Final:compile
[INFO]    org.jdom:jdom:jar:2.0.2:compile
[INFO]    org.eclipse.persistence:org.eclipse.persistence.asm:jar:2.6.0:compile
[INFO]    org.glassfish.jersey.containers:jersey-container-servlet-core:jar:2.24.1:compile
[INFO]    com.fasterxml.jackson.jaxrs:jackson-jaxrs-json-provider:jar:2.9.5:compile
[INFO]    org.glassfish:javax.json:jar:1.0.4:compile
[INFO]    com.google.transit:gtfs-realtime-bindings:jar:0.0.4:compile
[INFO]    antlr:antlr:jar:2.7.7:compile
[INFO]    xml-apis:xml-apis:jar:1.4.01:compile
[INFO]    ch.qos.logback:logback-classic:jar:1.1.3:compile
[INFO]    com.google.protobuf:protobuf-java:jar:2.6.1:compile
[INFO]    org.hornetq:hornetq-core-client:jar:2.3.25.Final:compile
[INFO]    org.glassfish.hk2:hk2-api:jar:2.5.0-b05:compile
[INFO]    com.simontuffs:one-jar-boot:jar:0.97.3:compile
[INFO]    javax.xml.bind:jaxb-api:jar:2.3.0:compile
[INFO]    ch.qos.logback:logback-core:jar:1.1.2:compile
[INFO]    org.glassfish.jersey.containers:jersey-container-servlet:jar:2.24.1:compile
[INFO]    org.jasypt:jasypt:jar:1.9.2:compile
[INFO]    com.github.haifengl:smile-math:jar:1.5.1:compile
[INFO]    commons-logging:commons-logging:jar:1.1.1:compile
[INFO]    commons-beanutils:commons-beanutils:jar:1.9.2:compile
[INFO]    javax.servlet:javax.servlet-api:jar:3.0.1:provided
[INFO]    org.glassfish.jersey.core:jersey-server:jar:2.24.1:compile
[INFO]    org.json:json:jar:20140107:compile
[INFO]    com.fasterxml.jackson.core:jackson-annotations:jar:2.9.0:compile
[INFO]    io.swagger.core.v3:swagger-core:jar:2.0.2:compile
[INFO]    org.jboss.spec.javax.jms:jboss-jms-api_1.1_spec:jar:1.0.0.Final:compile
[INFO]    com.google.guava:guava:jar:20.0:compile
[INFO]    com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:jar:2.9.5:compile
[INFO]    com.github.haifengl:smile-graph:jar:1.5.1:compile
[INFO]    io.swagger.core.v3:swagger-integration:jar:2.0.2:compile
[INFO]    mysql:mysql-connector-java:jar:5.1.35:compile
[INFO]    javax.mail:mail:jar:1.4.7:compile
[INFO]    com.mchange:c3p0:jar:0.9.2.1:compile
[INFO]    org.yaml:snakeyaml:jar:1.18:compile
[INFO]    org.glassfish.jersey.media:jersey-media-moxy:jar:2.24.1:compile
[INFO]    javax.validation:validation-api:jar:1.1.0.Final:compile
[INFO]    org.hibernate:hibernate-c3p0:jar:4.3.9.Final:compile
[INFO]    org.apache.commons:commons-lang3:jar:3.3.2:compile
[INFO]    org.slf4j:slf4j-api:jar:1.7.2:compile
[INFO]    dom4j:dom4j:jar:1.6.1:compile
[INFO]    org.hibernate:hibernate-core:jar:4.3.9.Final:compile
[INFO]    org.glassfish.jersey.media:jersey-media-jaxb:jar:2.24.1:compile
[INFO]    org.hornetq:hornetq-jms-client:jar:2.3.25.Final:compile
[INFO]    org.glassfish.hk2:hk2-utils:jar:2.5.0-b05:compile
[INFO]    org.javassist:javassist:jar:3.22.0-GA:compile
[INFO]    org.java-websocket:Java-WebSocket:jar:1.3.0:compile
[INFO]    commons-collections:commons-collections:jar:3.2.1:compile
[INFO]    org.glassfish.hk2:hk2-locator:jar:2.5.0-b05:compile
[INFO]    org.codehaus.jackson:jackson-core-asl:jar:1.9.12:compile
[INFO]    io.swagger.core.v3:swagger-jaxrs2:jar:2.0.2:compile
[INFO]    io.netty:netty:jar:3.6.10.Final:compile
[INFO]    org.hibernate.javax.persistence:hibernate-jpa-2.1-api:jar:1.0.0.Final:compile
[INFO]    org.jboss:jandex:jar:1.1.0.Final:compile
[INFO]    javax.activation:activation:jar:1.1:compile
[INFO]    org.postgresql:postgresql:jar:9.3-1103-jdbc41:compile
[INFO]    javax.ws.rs:javax.ws.rs-api:jar:2.0:compile
[INFO]    org.glassfish.jersey.ext:jersey-entity-filtering:jar:2.24.1:compile
[INFO]    org.jboss.logging:jboss-logging:jar:3.1.3.GA:compile
[INFO]    org.hsqldb:hsqldb:jar:2.2.4:compile
[INFO]    org.glassfish.jersey.core:jersey-common:jar:2.24.1:compile
[INFO]    org.glassfish.hk2.external:aopalliance-repackaged:jar:2.5.0-b05:compile
[INFO]    org.glassfish.jersey.bundles.repackaged:jersey-guava:jar:2.6:compile
[INFO]    commons-cli:commons-cli:jar:1.2:compile
[INFO]    org.webjars:swagger-ui:jar:3.17.1:compile
[INFO]    org.glassfish.hk2.external:javax.inject:jar:2.5.0-b05:compile
[INFO]    javax.annotation:javax.annotation-api:jar:1.2:compile
[INFO]    org.hibernate.common:hibernate-commons-annotations:jar:4.0.5.Final:compile
[INFO]    io.swagger.core.v3:swagger-annotations:jar:2.0.2:compile
[INFO]    org.glassfish.hk2:osgi-resource-locator:jar:1.0.1:compile
[INFO]    org.hornetq:hornetq-commons:jar:2.3.25.Final:compile
[INFO]    org.jboss.logging:jboss-logging-annotations:jar:1.2.0.Beta1:compile
[INFO]    org.apache.commons:commons-csv:jar:1.1:compile
[INFO]    org.apache.commons:commons-jcs-core:jar:2.2:compile
[INFO]    TheTransitClock:transitclockCore:jar:2.0.0-SNAPSHOT:compile
[INFO]    org.jboss.spec.javax.transaction:jboss-transaction-api_1.2_spec:jar:1.0.0.Final:compile
[INFO]    org.jgroups:jgroups:jar:3.2.13.Final:compile
[INFO]    org.eclipse.persistence:org.eclipse.persistence.core:jar:2.6.0:compile
[INFO]    org.reflections:reflections:jar:0.9.11:compile
[INFO]    com.esri.geometry:esri-geometry-api:jar:1.1:compile
[INFO]    org.eclipse.persistence:org.eclipse.persistence.moxy:jar:2.6.0:compile
[INFO]    com.fasterxml.jackson.jaxrs:jackson-jaxrs-base:jar:2.9.5:compile
[INFO]    com.fasterxml.jackson.core:jackson-databind:jar:2.9.5:compile
[INFO]    io.swagger.core.v3:swagger-models:jar:2.0.2:compile
[INFO]    com.fasterxml.jackson.module:jackson-module-jaxb-annotations:jar:2.9.5:compile
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.102 s
[INFO] Finished at: 2018-09-08T18:18:56+01:00
[INFO] Final Memory: 17M/212M
[INFO] ------------------------------------------------------------------------

**Comment by scrudden** [comment]
Think is my mistake.  I built this locally without doing a clean. Will rebuild and try again.

**Comment by scrudden** [comment]
Tried again and all OK, so closing.

**Comment by vsperez** [comment]
Excellent!!
