### ISSUE TITLE
resetVehicle automation

### ISSUE THREAD

**Issue by changtung** [TheTransitClock/transitime#114]
I would like to add functionality of automatic resetVehicle, when some trip is late more than specified criteria. Currently if that situation occurs, i see on _schAdhMap_
 vehicles and when some are in big circle, i want to call _resetVehicleApiParams_ on that vehicles. 
What is the best way to implement this - as a module and when i add this module, then it works ? 
I don't want to do changes in transitime core, in order to do this.

**Comment by scrudden** [comment]
Hi,

I think the org.transitclock.core.TimeoutHandlerModule should help with the situation you describe and in particular this method.

https://github.com/TheTransitClock/transitime/blob/787afd5905e1f29d1bb5377364367e74451ed13d/transitclock/src/main/java/org/transitclock/core/TimeoutHandlerModule.java#L167-L195

Cheers,

Sean.

**Comment by scrudden** [comment]
@pacior Did this help? Can I close?

**Comment by scrudden** [comment]
Closing as no response since 2018.
