### ISSUE TITLE
GtfsFileProcessor does not update database but does not report an error

### ISSUE THREAD

**Issue by oofpez** [TheTransitClock/transitime#116]
When running the GtfsFileProcessor.jar with a config file and GTFS (either file or URI), it prints out "Processing configuration file" then exits without updating the database.  I cannot figure out what I'm doing wrong, or if there is an issue with the code.

When using the docker project, I encounter the same issue where that stage of the script doesn't result in the database being updated.

**Comment by scrudden** [comment]
There would normally be logback log files created. One would be core.log. If you can locate this file it may have information on what your issue is. In the docker container it would be in the dated subdirectory of /usr/local/transitclock/logs.

Failing this if you clone the Docker project and modify it for your configuration I can have a look.

**Comment by oofpez** [comment]
I can't find any .log files. after running the GtfsFileProcessor.jar, gave up on that and tried docker...

I used the unmodified docker project by running the commands in go.sh one by one.
(on Windows with Linux Docker containers)

Nothing seemed to have issues until I ran the command with ./process_avl.sh
it started printing exceptions - see [paste1](https://pastebin.com/ubcEdjLB) and [paste2](https://pastebin.com/TwukPJ6R)

then when I ran

> docker run --name transitclock-server-instance --rm --link trans
> itclock-db:postgres -e PGPASSWORD=$PGPASSWORD  -p 8080:8080 transitclock-server  ./start_transitclock.sh

I got 

> THETRANSITCLOCK DOCKER: Start TheTransitClock.
> JAVA_OPTS -Dtransitime.apikey=f78a2e9a
> Tomcat started.
> Error parasing XML file "/usr/local/transitclock/config/transitckockConfig.xml" : /usr/local/transitclock/config/transitckockConfig.xml (No such file or directory)
> org.transitime.config.ConfigFileReader$ConfigException: java.io.FileNotFoundException: /usr/local/transitclock/config/transitckockConfig.xml (No such file or directory)

I checked inside the docker container and there were no useful logs, just

> WebLoggingFilter init
> ApiLoggingFilter init

**Comment by scrudden** [comment]
I would suggest you clone the Docker project and use the MBTA_trial branch as a starting pointing point. 

If you configure this as best you can I can have a look.

**Comment by oofpez** [comment]
Thanks, using that branch helped

**Comment by oofpez** [comment]
I'm having trouble using my own GTFS file though.  At first I tried via url, then via zip.

I think something is wrong with my config but I can't figure out what.
Please check this branch on a fork of this repo with a supplied GTFSfile:
https://github.com/oofpez/transitime/tree/trying-gautrain-config

When I run the import_gtfs stage, I get UPDATE 0 as a result with no change to the database.

**Comment by scrudden** [comment]
Remove this line and it should import. This was filtering for a single MBTA route 66.

https://github.com/oofpez/transitime/blob/ead7c12cd54ee2d17051de7313a1bc73adfb07d3/config/transitclockConfig.xml#L6

**Comment by oofpez** [comment]
Thanks for the help!
got it working :)

btw, this is unrelated to the issue but perhaps you could help me:
I'm trying to push AVL to the api, and it says

```
 {
    "success": true,
    "message": "AVL processed"
}
```

(data is https://pastebin.com/ujTCrvFH )

but server status says 

> Last valid AVL report was 1545912761 secs old while allowable age is 300 secs as specified by parameter transitclock.monitoring.allowableNoAvlSecs .

and these avl don't show up in the map or anywhere.  How can I know what's happening to them?

**Comment by scrudden** [comment]
You may need to set the timezone for your location in this file.

https://github.com/TheTransitClock/transitclockDocker/blob/52c8b42461aac5338af257f27d88ac8574267c2c/bin/start_transitclock.sh#L24

**Comment by oofpez** [comment]
Thanks did that.

It still says the last valid avl report was (epoch timestamp) secs old though - as if it were reading in my AVLs as if they had timestamp of 0, or they are just lost.
Would the last avl report per vehicle include avl's that weren't matched to a route? I don't see any at all.

EDIT: Ah the logs reveal minlatitude and maxlatitude make my avl out of bounds :)

**Comment by oofpez** [comment]
Can't find where to set transitclock.avl.minLatitude though, could you point me in the right direction?
