### ISSUE TITLE
Add front end for resetVehicle api call.

### ISSUE THREAD

**Issue by scrudden** [TheTransitClock/transitime#14]
resetVehicle is an API call added during the implementation of DynamicTime for when we would see that a vehicle was assigned to the wrong segment. The most noticeable symptom was the arrow for direction would be pointing in the wrong direction.

A call to this makes the vehicle unpredictable and the system will then reassign correctly. 

This call takes a single parameter "v" which is the vehicle id.

**Comment by scrudden** [comment]
It would be good to change this API call to also record an VehicleEvent to say that the vehicle was made unpredictable via the API.

**Comment by changtung** [comment]
I see recording vehicleEvent in line 118 in CommandsServer.java. 
`		VehicleEvent.create(avlReport, lastMatch, vehicleEvent,
				eventDescription, false, // predictable
				wasPredictable, // becameUnpredictable
				null); // supervisor`
I see that in resetVehicle call there is call to setVehicleUnpredictable from CommandServer, so the code above is beeing run. 
So is there need to implement it?

**Comment by scrudden** [comment]
It is there already so there is no need to implement.

**Comment by scrudden** [comment]
Being worked on in this pull request.

https://github.com/TheTransitClock/transitime/pull/16

**Comment by scrudden** [comment]
merged into VIA branch

**Comment by changtung** [comment]
ok, thank You:)
