### ISSUE TITLE
The import io.swagger.client cannot be resolved

### ISSUE THREAD

**Issue by sreeharibs** [TheTransitClock/transitime#145]
I just checked out TransitClock and have the following error in `TransitclockCore/TraccarAVLModule.java`

`The import io.swagger.client cannot be resolved`

How to resolve the same ?

**Comment by scrudden** [comment]
Have you built the project using maven or is this an error from your IDE(eclipse)?

**Comment by scrudden** [comment]
Hi @sreeharibs,

Can I close this?

Thanks,

Sean.

**Comment by sreeharibs** [comment]
> Hi @sreeharibs,
> 
> Can I close this?
> 
> Thanks,
> 
> Sean.

Sorry! I missed your comment. 

> Have you built the project using maven or is this an error from your IDE(eclipse)?

I built it on Eclipse.

**Comment by scrudden** [comment]
Can you build with maven? The maven build generates source files from swagger files. Once you have built with maven you should be then able to include these generated files in the source path in the eclipse project.

**Comment by scrudden** [comment]
no update so closing.
