### ISSUE TITLE
How can I launch a multi-agency configuration of TheTransitClock?

### ISSUE THREAD

**Issue by ciolt** [TheTransitClock/transitime#149]
Hi,

I'm working on a real-time transit system in South Florida, and I can't seem to get the dockerized TC (see: [transitclockDocker@MBTA_Trial](https://github.com/TheTransitClock/transitclockDocker/tree/MBTA_trial)) to work. It keeps throwing database connections errors in my [cscape/wayline-interchange](https://github.com/cscape/wayline-interchange) repo and I'm not entirely sure why. It may have something to do with the setup and how it's launched.

The [wiki article](https://github.com/TheTransitClock/transitime/wiki/Multi-agency-configuration) about multi-agency config is unclear on how commands should be run chronologically and why. So far it's marginally helped but TC still doesn't run successfully. I'd like to know how exactly one would go about launching TC with multiple agencies, in terms of a list of which commands go when.

Just a basic idea of what I'm doing:
- Using PostgreSQL (psql)
- Using 2 agencies, for simplicity
  - **Halifax Transit**
Database/Agency ID: `halifax_transit`
GTFS-Realtime: `http://gtfs.halifax.ca/realtime/Vehicle/VehiclePositions.pb`
GTFS URL: `http://gtfs.halifax.ca/static/google_transit.zip`
  - **Hillsborough Area Regional Transit**
Database/Agency ID: `tampa`
GTFS-Realtime: `http://api.tampa.onebusaway.org:8088/vehicle-positions`
GTFS URL: `http://www.gohart.org/google/google_transit.zip`

Haven't really had any luck getting this to work. Help is greatly appreciated, thank you!

**Comment by scrudden** [comment]
There are two issues here.

1. The docker installer failing.
2. An explanation of the commands used to do a multi-agency installation.

**Comment by scrudden** [comment]
The docker installer has had problems recently due to the archiving of some debian packages. I will look at this one and update one of the branches to work with a newer FROM than maven:3.3-jdk-8. This should sort this out.

**Comment by ciolt** [comment]
I'm aware of the Docker installer's problem, and my Docker container works just fine (after changing the image and making some other changes). Of course, I can't launch TC properly if I don't know how to do it. I believe Swiftly uses a multi-agency installation, though.

**Comment by scrudden** [comment]
@vsperez has updated the wiki with more information. I hope this helps.

There is some more (incomplete) doucmentation here [docs](https://github.com/TheTransitClock/transitime/tree/shade_build_upstream/transitime)

**Comment by ciolt** [comment]
Thanks Sean (and @vsperez), I have it working now. 👍

**Comment by ciolt** [comment]
Update: I've clarified the documentation on the wiki a little further (with a diagram).

Should be easier now to understand: https://github.com/TheTransitClock/transitime/wiki/Multi-Agency-Configuration

**Comment by scrudden** [comment]
Thanks. That's great!!!
