### ISSUE TITLE
transitimeDocker postgresql version

### ISSUE THREAD

**Issue by changtung** [TheTransitClock/transitime#15]
In transitimeDocker, latest version of postgresql is not working when running go.sh. 
In go.sh there is command `docker run --name transitime-db -e POSTGRES_PASSWORD=$PGPASSWORD -d postgres`
i needed to change it to: 
`docker run --name transitime-db -e POSTGRES_PASSWORD=$PGPASSWORD -d postgres:9.6.3`

It is because new version of postgres is 10.x and it turns out that it's not compatible with current transitimeDocker.

**Comment by scrudden** [comment]
Fix added to master branch.

https://github.com/TheTransitClock/transitimeDocker/commit/352da400af461559b37d96c7e35a9c665c537f92

Will need to change in all other branches.

**Comment by scrudden** [comment]
Have changed in all branches of transiTimeDocker.
