### ISSUE TITLE
Problem with tomcat connecting to postgresql ? 

### ISSUE THREAD

**Issue by changtung** [TheTransitClock/transitime#22]
Hi, I have problem with transitime instance. one works on port 8097, which has code from same branch, use different databases. tomcat version is same. recently i created new database. i have error, connection attempt failed on transitime web . is it possible that jar is connecting succesfully to postgres ,tomcat no and i can connect locally through 127.0.0.1 ( not localhost ) . 
So one instance on port 8096 doesnt connect tomcat, second version does connect. 
tomcat versions - same
code from repository - same
transitime modules added - same

**Comment by scrudden** [comment]
Hi,

I am not sure I understand your setup. Can you first detail how you have
set up the database for each transiTime instance?

Cheers.

Sean.

**Comment by scrudden** [comment]
@pacior  Can this issue be closed?

**Comment by changtung** [comment]
I think yes. We avoided this problem by setting instance on another database port. However problem exist in our infrastructure as a bug.

**Comment by scrudden** [comment]
As per comment from @pacior closing issue.
