### ISSUE TITLE
[BUG] QuickStart Maven Build Failure - Missing ressource

### ISSUE THREAD

**Issue by brodyFlannigan** [TheTransitClock/transitime#222]
**Expected functionality**
When the `mvn install -DskipTests` command is run, the build should succeed.
**Describe the bug**
The build fails. Maven reports the following: ` Failed to execute goal on project transitclockQuickStart: Could not resolve dependencies for project TheTransitClock:transitclockQuickStart:jar:2.0.0-SNAPSHOT: Could not find artifact TheTransitClock:transitclockCore:jar:2.0.0-SNAPSHOT -> [Help 1]
`
The full console log from Maven is attached.
[TransitClock_Log_Fail.txt](https://github.com/TheTransitClock/transitime/files/5752427/TransitClock_Log_Fail.txt)

**To Reproduce**
1. Get the latest version of the `develop` branch of TransiTime.
2. Run `mvn install -DskipTests` in the `transitclockQuickStart` directory
3. Watch the console output

**Screenshots**
Please see [TransitClock_Log_Fail.txt](https://github.com/TheTransitClock/transitime/files/5752427/TransitClock_Log_Fail.txt)

**Version:**
Latest version of the `develop` branch as of December 29, 2020.

**Configuration:**
OS: Win7 Pro
Maven: 3.6.3
Java: JDK 1.8.0

**Additional context**
Happy New Year!

**Comment by scrudden** [comment]
Happy New Year! 

Can you try build from the parent directory of transitclockQuickStart?

**Comment by brodyFlannigan** [comment]
The build succeeded when built from the parent directory (transitime-develop in my case).

Closing issue.
