### ISSUE TITLE
Cannot build because of moved dependency repo

### ISSUE THREAD

**Issue by BodoMinea** [TheTransitClock/transitime#250]
**Expected functionality**
Being able to build the project with `mvn install -DskipTests` after cloning from GitHub.

**Describe the bug**
The build fails with the following message:
`[ERROR] Failed to execute goal on project transitclockCore: Could not resolve dependencies for project TheTransitClock:transitclockCore:jar:2.0.0-SNAPSHOT: Failed to collect dependencies at com.simontuffs:one-jar-boot:jar:0.97.3: Failed to read artifact descriptor for com.simontuffs:one-jar-boot:jar:0.97.3: Could not transfer artifact com.simontuffs:one-jar-boot:pom:0.97.3 from/to maven-default-http-blocker (http://0.0.0.0/): Blocked mirror for repositories: [bintray-kevinlee-maven (http://dl.bintray.com/kevinlee/maven, default, releases)] -> [Help 1]`

**To Reproduce**
Please provide an example where TheTransitClock is not behaving as expected. The related datasets showing this example, which may come from several tables within TheTransitClock, should be provided along with a short description. 

**Additional context**
After encountering this issue and looking around, it seems like I am not the first one to run into this hiccup. There's an issue on the one-jar-boot repo mentioning thetransitclock - https://github.com/Kevin-Lee/one-jar-boot/issues/5
Looks like the host mentioned for the repo in pom.xml is now defunct (bintray).

I was able to solve this for myself by configuring the dependency to be pulled directly from Maven Central. I opened PR #249 with this change, if you want to integrate it.

Thanks!

**Comment by scrudden** [comment]
Thanks, I will merge the pull request.

**Comment by BodoMinea** [comment]
Okay, this is solved. Thanks!
