### ISSUE TITLE
Schedule adherence reports shows incorrect info

### ISSUE THREAD

**Issue by wkulesza** [TheTransitClock/transitime#256]
**Expected functionality**
When requesting report on schedule adherence for trips/blocks from a given trip, report should show true information.

**Describe the bug**
We extended schedule adherence reports and we have the ability to identify trips/blocks that were early/late, as opossed to only show % bar of early/late. Reports indicate that a given trip was early leaving 1st stop, while comparing this to relevant AVL report (of that bus serving that trip) indicate that the bus was in fact late (and not early)

**To Reproduce**
Grab our version of transitime, use your data and verify schedule adherence reports with avl reports.

**Screenshots**
Schedule adherence report: https://prnt.sc/EG6iPcRNOiLw
AVL report: https://prnt.sc/Tsi2c7BAXiVU
Schedule: https://prnt.sc/jvo6MTaB0Mgk

**Version:**
[https://github.com/goeuropa/transitime-1/tree/goeuropa_2](url)

**Configuration:**
Use config provided

**Comment by wkulesza** [comment]
Additonal information would include info that there's two different routes leaving that first stop, but since we're joining trips through blocks so transitclock should "know" which bus is on which next trip, while it's waiting for start of trip on the bus terminus.

**Comment by scrudden** [comment]
You would need to look at the matching for this bus and if it matched incorrectly too early. If so, this would indicate some configuration parameter changes should help.

**Comment by wkulesza** [comment]
@scrudden So the case is the following:
bus reaches final stop on its trip (stop-id is unique). After all passengers dissembark, bus moves to a given bus platform (stop id is different than the last one)  and straight away it is matched to the next trip (TC then says in matching that bus departed early), while in fact the trip only starts in some 10-15 mins.
End result is - majority of 1st departures from that stop id are marked as early - while in reality, its not.

**Comment by wkulesza** [comment]
Please mark as solved. This turned out to be a problem with location of departure stop. it was set in a wrong spot, which caused TC to show departure from stop, while in fact, bus was only moving to departure platform.
