### ISSUE TITLE
How to make transitime password accessible

### ISSUE THREAD

**Issue by changtung** [TheTransitClock/transitime#28]
How to force users to enter credentials in order to log in to transitime? Is there any module with this ?

**Comment by scrudden** [comment]
You can do this with tomcat configuration.

For basic authentication have a look at 

[http://wiki.metawerx.net/wiki/SecuringYourSiteWithContainerManagedSecurity](http://wiki.metawerx.net/wiki/SecuringYourSiteWithContainerManagedSecurity)

**Comment by scrudden** [comment]
@pacior Can this issue be closed?

**Comment by scrudden** [comment]
No response so closing.
