### ISSUE TITLE
Unexpected match ( prediction ) 

### ISSUE THREAD

**Issue by changtung** [TheTransitClock/transitime#29]
On basic data, i have prediction for device id 5089. 
On map it stops and gps data is always same latitude and longtitude. Transitime guesses prediction of this device and assign it a route. Below are logs where it take place. 

> 10:35:01.082 Calling prediction algorithm for AvlReport [vehicleId=5089, time=01-15-2018 11:34:48.000 CET, timeProcessed=01-15-2018 11:35:01.082 CET, location=[52.22040, 17.05890], speed=NaN, heading=0.0 deg, source=5089, assignmentId=null, assignmentType=UNSET] with a match TemporalMatch [temporalDifference=-64.8 min (late), avlTime=01-15-2018 11:34:48.000 CET, blockId=2A, tripIndex=5, gtfsStopSeq=1, stopPathIndex=0, segmentIndex=0, isLayover=true, distanceToSegment=10537.91m, distanceAlongSegment=0.00m, distanceAlongStopPath=0.00m, atStop=Indices [blockId=2A, tripIndex=5, stopPathIndex=0, stopId=54], trip=Trip [tripId=560_tam_12345__10:30, tripShortName=560_tam_12345__10:30, tripPatternId=shape_560__35_54_to_STOP_9a868fa_d75f345d, tripIndexInBlock=5, startTime=10:30:00, endTime=11:27:00, headsign="Poznań - Rataje Dworzec", directionId=0, routeId=560, routeShortName=560, serviceId=R12345, blockId=2A, shapeId=560__35]].
10:35:01.082 For vehicleId=5089 the original arrival time for waitStop stopId=54 is 01-15-2018 11:34:48.000 CET
10:35:01.082 For vehicleId=5089 adjusted the arrival time for layover stopId=54 tripId=560_tam_12345__10:30 blockId=2A since crowFliesTimeToLayover=1203790 but predictionTime-avlReport.getTime()=0msec. The arrival time is now 01-15-2018 11:54:51.790 CET
10:35:01.082 For vehicleId=5089 adjusted departure time for wait stop stopId=54 tripId=560_tam_12345__10:30 blockId=2A to expectedDepartureTimeWithStopWaitTime=01-15-2018 11:54:51.790 CET because arrivalTime=01-15-2018 11:54:51.790 CET but scheduledDepartureTime=01-15-2018 10:30:00.000 CET and expectedStopTimeMsec=0
10:35:01.082 Generated prediction IpcPrediction [vehicleId=5089, predTime=01-15-2018 11:54:51 CET, routeId=560, rteName=560, stop=54, gtfsStopSeq=1, tripId=560_tam_12345__10:30, freqStartTime=00:59:59.999, tripPatternId=shape_560__35_54_to_STOP_9a868fa_d75f345d, blockId=2A, avlTime=11:34:48.000, createTime=11:35:01.082, tripStartEpochTime=10:30:00.000, atEndOfTrip=f, waitStop=t, arrival=f] based on avlreport AvlReport [vehicleId=5089, time=01-15-2018 11:34:48.000 CET, timeProcessed=01-15-2018 11:35:01.082 CET, location=[52.22040, 17.05890], speed=NaN, heading=0.0 deg, source=5089, assignmentId=null, assignmentType=UNSET].

> 
It is written "because of schedule time". Or how to interact with this value, prediction.

**Comment by scrudden** [comment]
Sorry, but I do not understand the issue/question. Can you give more detail?

**Comment by changtung** [comment]
Transitime assigns trip to a vehicle not correct one. 
If there are two vehicles and one is stopping, second drives to a point where it starts, transitime assigns trip for the one that is stopping, not the one that goes that trip. Is there param for prediction approximation? param to change approximation from 40 to 20 mins for example?

**Comment by scrudden** [comment]
In **_org.transitime.core.autoAssigner.AutoBlockAssigner_** there are some config values that might help.

Perhaps this one would help in this situation.

```
private static DoubleConfigValue minDistanceFromCurrentReport =
			new DoubleConfigValue(
					"transitime.autoBlockAssigner.minDistanceFromCurrentReport", 
					100.0, 
					"AutoBlockAssigner looks at two AVL reports to match "
					+ "vehicle. This parameter specifies how far away those "
					+ "AVL reports need to be sure that the vehicle really "
					+ "is moving and in service. If getting incorrect matches "
					+ "then this value should likely be increased.");
```

**Comment by changtung** [comment]
I changed value to 200 and then 2000 and both have still this error. 
Which Api call can i use to unassign vehicle ? What are url and params of this api call?

**Comment by scrudden** [comment]
This issue (#14) has the detail on how to unassign a vehicle  .

**Comment by scrudden** [comment]
These two parameters may help have the vehicle that is not moving be unassigned automatically.
```
	private static IntegerConfigValue timeForDeterminingNoProgress =
			new IntegerConfigValue(
					"transitime.core.timeForDeterminingNoProgress", 
					8 * Time.MS_PER_MIN, 
					"The interval in msec at which look at vehicle's history "
					+ "to determine if it is not making any progress. A value"
					+ "of 0 disables this feature. If "
					+ "vehicle is found to not be making progress it is "
					+ "made unpredictable.");
			
	public static double getMinDistanceForNoProgress() {
		return minDistanceForNoProgress.getValue();
	}
	private static DoubleConfigValue minDistanceForNoProgress =
			new DoubleConfigValue(
					"transitime.core.minDistanceForNoProgress",
					60.0,
					"Minimum distance vehicle is expected to travel over "
					+ "timeForDeterminingNoProgress to indicate vehicle is "
					+ "making progress. If "
					+ "vehicle is found to not be making progress it is "
					+ "made unpredictable.");
```

**Comment by scrudden** [comment]
@pacior Can this issue be closed?

**Comment by scrudden** [comment]
No response so closing.
