### ISSUE TITLE
Add traccar integration

### ISSUE THREAD

**Issue by scrudden** [TheTransitClock/transitime#46]
@pacior has integrated with [traccar](http://www.traccar.org) on his fork. This module would be a nice addition to the TheTransitClock.

**Comment by scrudden** [comment]
Have worked on this on branch tc_issue_46. 

I used the swagger file supplied with traccar to generate the client code and used that to create a transitclock avl module.

The client code is generated by a maven plugin.

**Comment by scrudden** [comment]
Pull request #47

**Comment by wkulesza** [comment]
Does Traccar integration work also with https rather than http ?
From [https://www.traccar.org/secure-connection/](url) they say we should use ws:// rather than https ?
