### ISSUE TITLE
Work as a tester

### ISSUE THREAD

**Issue by marzena92** [TheTransitClock/transitime#49]
Hi!
I will eagarly do a job as a tester in a project transitime. 
Regards

**Comment by changtung** [comment]
Sean, marzena92 is a person I recommend 100%. I am curious what could be her first testing task.

**Comment by scrudden** [comment]
@marzena92
Thanks for the interest. It is very welcome.

@pacior This may need a quick call to get started. Perhaps a hangout next week?

Before then just setting up an example system locally may be a good start.

**Comment by scrudden** [comment]
no recent response so closing.
