### ISSUE TITLE
Shutting down instances running on Open Austin AWS

### ISSUE THREAD

**Issue by mateoclarke** [TheTransitClock/transitime#5]
Hi @scrudden,

Our hosting with CfA is being audited and we found that our biggest charges are coming from old transitime instances that @luqmaan helped set up.

We need to shut down these instances but I didn't want to catch you off guard. Tried msg'ing you through Slack so hoping this reaches you.

![pasted image at 2017_04_15 06_18 pm](https://cloud.githubusercontent.com/assets/5697474/25098200/3d1f7c94-236d-11e7-8d95-8deb00d479b3.png)

**Comment by scrudden** [comment]
Hi Mateo,

Go ahead and remove them. I am not using them.

Thanks,

Sean.
