### ISSUE TITLE
Active blocks and vehicle assignments for stops with different arrival and departure times

### ISSUE THREAD

**Issue by nselikoff** [TheTransitClock/transitime#50]
I'm working with a GTFS static feed whose first two stops are at train stations where the vehicle waits for ~15 minutes before departing. One of these stops is the first stop of the trip. Also, it's a continuous loop (same block ID throughout the day, first and last stops are the same, and departure_time of the last stop == arrival_time of the first stop of the subsequent trip.

For real-time, I'm working with raw GPS data without trip assignments.

I'm running into two issues, which may just be a matter of configuration:
1. No active blocks are detected until the departure_time from the first stop of the trip. E.g. if the first stopTime arrival_time is 12:00:00, and departure_time is 12:15:00, there are no active blocks until 12:15:00. This is one root cause for the vehicle remaining unassigned / unpredictable. Shortly after the vehicle departs the station, as long as it's after 12:15:00, it gets assigned to the trip.
2. At the second stop, the vehicle waits for 10 minutes (between arrival_time and departure_time). Here it gets unassigned, I think because `transitclock.autoBlockAssigner.minDistanceFromCurrentReport` is set to its default value.

Can you provide any insight on the best configuration for this scenario?

**Comment by scrudden** [comment]
Hi Nathan,

Can you see entries in the vehicle event table for item 2? 

Also, have you got debug logging on and can you find the detail of the same event in these log files. If I could see your logback configuration I could point you at which file to look at.

Cheers,

Sean.

**Comment by nselikoff** [comment]
Hi Sean, thanks for the quick reply. I think I'm using default logging (I'm not specifying a logback.xml), which I guess would be https://github.com/TheTransitClock/transitime/blob/develop/transitclock/src/main/resources/logback.xml or https://github.com/TheTransitClock/transitime/blob/develop/transitclock/src/main/resources/logbackDefault.xml ? I've got quite a few log files being created and used.

I'll work on pulling up the vehicle event entries.

**Comment by nselikoff** [comment]
@scrudden actually it looks like a few things are going on. Here are some of the vehicle event entries:

```
time | eventtype | description | tripid
2018-04-26 12:15:24.102 | Predictable | Vehicle successfully matched to block assignment and is now predictable. | TUE_WED_THU_1200
2018-04-26 12:17:14.119 | No match    | Vehicle had schedule adherence of 15.5 min (early) which is beyond acceptable limits. Therefore vehicle made unpredictable. | TUE_WED_THU_1200
2018-04-26 12:29:44.235 | Predictable | Vehicle successfully matched to block assignment and is now predictable. | TUE_WED_THU_1200
2018-04-26 12:59:29.491 | No match    | Vehicle had schedule adherence of 52.5 min (early) which is beyond acceptable limits. Therefore vehicle made unpredictable. | TUE_WED_THU_1300
2018-04-26 12:59:59.492 | Predictable | Vehicle successfully matched to block assignment and is now predictable. | TUE_WED_THU_1200
2018-04-26 13:15:14.627 | No match    | Vehicle had schedule adherence of 43.2 min (early) which is beyond acceptable limits. Therefore vehicle made unpredictable. | TUE_WED_THU_1300
2018-04-26 13:26:44.719 | Predictable | Vehicle successfully matched to block assignment and is now predictable. | TUE_WED_THU_1300
```

I'm not sure where the 15.5 min early schedule adherence is coming from. That's basically right after the vehicle leaves the station. Similar pattern an hour later, though it's 43.2 min for some reason.

Then at the very end of the 1200 trip, it incorrectly matches to the 1300 trip before flipping back to the 1200 trip.

**Comment by scrudden** [comment]
The logback config file you are using is https://github.com/TheTransitClock/transitime/blob/develop/transitclock/src/main/resources/logback.xml.

Thought so far. It keeps auto assigning to the 1200 trip and then checks schedule adherence using that trip and as it has gone past acceptable limits in each case it marks it as unpredictable.

So the problem is that it is not assigning it to the correct trip. Why I'm not sure. The detail on this may/should be in the matcher log files. Can you list the log files you have?

**Comment by nselikoff** [comment]
arrivalDeparture.log
autoAssigner.log
avl.log
cache.log
core.log
externalPredAccuracy.log
frequency.log
match.log
matcher.log
monitoring.log
predAccuracy.log
prediction.log
vehicleEvents.log

**Comment by scrudden** [comment]
In logback.xml can you change these two entries
```
<logger name="org.transitclock.core.TemporalMatcher" level="info" additivity="true"> 
		<appender-ref ref="MATCHER" /> </logger> 
	<logger name="org.transitclock.core.SpatialMatcher" level="info" additivity="true"> 
		<appender-ref ref="MATCHER" /> </logger>
```
to level="debug" like this

```
<logger name="org.transitclock.core.TemporalMatcher" level="debug" additivity="true"> 
		<appender-ref ref="MATCHER" /> </logger> 
	<logger name="org.transitclock.core.SpatialMatcher" level="debug" additivity="true"> 
		<appender-ref ref="MATCHER" /> </logger>
```

This should give some decent info in the matcher.log file relating to the problem.

**Comment by nselikoff** [comment]
Thank you, I've got that updated and will keep an eye on matcher.log.

**Comment by nselikoff** [comment]
Found at least one of the issues... timezone mismatch. I hate timezones and daylight savings time LOL. I'm borrowing some of the scripts from the `transitclockDocker` project, which has the user.timezone set to EST (a non- daylight savings time sensitive value). So I was getting an hour off between the agency timezone and some other part of the system that was using the default time zone.

**Comment by nselikoff** [comment]
Dug in a bit more to item 1. In [BlocksProcessor](https://github.com/TheTransitClock/transitime/blob/develop/transitclock/src/main/java/org/transitclock/gtfs/BlocksProcessor.java#L225), block start time is set as first trip start time, which is set as *departure* time of the first stop time. But the GTFS static spec notes that if the stop_time is a timepoint, which it is in the case of this feed, arrival_time must be set. So in this feed we have the first trip's arrival time of 12:00:00, departure time of 12:15:00, and timepoint = 1. The only way I can see to indicate to TheTransitClock that the block should be active at 12:00:00 is to add some logic for this in the code. What do you think @scrudden?

**Comment by scrudden** [comment]
Hi Nathan,

What modules have you configured to run in your transitclockConfig.xml file?

I think using the [org.transitclock.core.schedBasedPreds.SchedBasedPredsModule](https://github.com/TheTransitClock/transitime/blob/develop/transitclock/src/main/java/org/transitclock/core/schedBasedPreds/SchedBasedPredsModule.java) module will help with item 1. 

Cheers,

Sean.

**Comment by nselikoff** [comment]
GtfsRealtimeModule and PredictionAccuracyModule. I will try out SchedBasedPredsModule.

**Comment by nselikoff** [comment]
With SchedBasedPredsModule and adjustments to some of its config params, I'm able to get predictions right away in the 12-12:15 window before the block becomes active. And even though the vehicle remains unassigned until a little after 12:15, it still shows up in the GTFS Realtime vehicle positions feed, which is good. This is a great start, thanks so much for the help!
