### ISSUE TITLE
How to capture an AVL sample and use it for testing and batch processing?

### ISSUE THREAD

**Issue by nselikoff** [TheTransitClock/transitime#53]
When setting up TheTransitClock for a new agency, there's so many options when it comes to configuration. And since we're dealing with real-time data it can be hard to tweak the config and see the effects efficiently.

What's the best way to capture an AVL sample (e.g. from a GTFS Realtime vehicle positions feed) and then using it for testing and batch processing in TheTransitClock? I see some areas in the codebase that seem to support this, and I'd love to be able to replay a set of data to test out different changes quickly.

**Comment by scrudden** [comment]
Hi Nathan,

The basics of this is to use the PlaybackModule module. You configure this to run in the transitclock config file like any other module. 

This has a number of options, including **playbackStartTime** and **playbackEndTime** so you can focus on the particular event you are looking at.

I also added an option **playbackRealtime** which if set to true will run at normal time speed, but if set to false will process the data as fast as possible. If set to false it also skips the times with no AVL data.

There is an example config here 
https://github.com/TheTransitClock/transitclockDocker/blob/prediction_comparison_hart/config/test/transitclockConfig1.xml

This PlaybackModule reads data from the avlrecords table. The avlrecords table will have data that has already been recorded while running the system live.

I have tended to do a new install on my development machine using transitclockDocker and copy the avlrecords from the live database into the development database, then connect a version of core (configured to run playback) running in Eclipse to this test database. 

On each run I clear some of the database tables with the following sql. https://gist.github.com/scrudden/2af5924f92859712934a3e9a1d15e286

There is an option **playbackVehicleId** which lets you only play back data from a single vehicle.

I hope this helps.

Cheers,

Sean.

**Comment by nselikoff** [comment]
Thanks for the rundown @scrudden! This is definitely enough for me to get started.

**Comment by nselikoff** [comment]
@scrudden have you used the PlaybackModule in conjunction with the autoAssigner before? When I run playback of a feed without block assignments, the autoAssigner uses the currently active blocks, not the blocks that would have been active at the time the AVL records were recorded. For example, it's Monday and I'm playing back data from Friday, but it's getting assigned to Monday's block and trips.

**Comment by scrudden** [comment]
This is an issue. We will need to create a test to cover this and then fix. I will raise a new issue for this.

**Comment by scrudden** [comment]
https://github.com/TheTransitClock/transitime/issues/56

**Comment by scrudden** [comment]
I have recently used this parameter to avoid saving data generated in playback mode to the database.
```
private static BooleanConfigValue storeDataInDatabase =
			new BooleanConfigValue("transitclock.db.storeDataInDatabase",
					true,
					"When in playback mode or some other situations don't " +
					"want to store generated data such as arrivals/" +
					"departures, events, and such to the database because " +
					"only debugging.");
```
