### ISSUE TITLE
Swagger file for API

### ISSUE THREAD

**Issue by scrudden** [TheTransitClock/transitime#55]
A Swagger file for the API would be useful for others.

**Comment by vsperez** [comment]
Hi. I almost finished the description of TransitimeApi class.  In order to finish it I need help with the description of /command/vehicleAdherenceSummary and its parameters 
allowableEarlySec, allowableLateSec and allowableBeforeTimeSecs.  Thanks in advance.
Regards
Vicente

**Comment by scrudden** [comment]
Hi Vicente,

These are to inform the counters for the number of current vehicles running early, late or on time.

The allowEarlySec is the number of seconds early a vehicle has to be before it is considered in the early counter.

The allowableLateSec is the number of seconds late a vehicle has to be to be considered in the late counter.

All current vehicles between these counters are added to the on time counter.

The allowableBeforeTimeSecs is used to work out the current set of vehicles to include in totals. From the comments in the source for the activeBlocks call.

"A block will be active if the time is between the block start time minus allowableBeforeTimeSecs and the block end time. Default value for allowableBeforeTimeSecs".

The calls in the source could do with comments on each. Most have, but there are a few missing.

Cheers,
Sean.

**Comment by vsperez** [comment]
Pull request added:
- Add swagger 3 support. #72
