### ISSUE TITLE
couple new reports. 

### ISSUE THREAD

**Issue by changtung** [TheTransitClock/transitime#6]
Hello i have question regarding transitime
the VIA branch has many classes modified in comparision to master transitime branch. Hence we were using master recently, we had scheduleAdherenceByStop report there. Currently in VIA branch, we want to have these reports too.
I tried to add some modules to config from previous app and i don't know where these reports reside. if that is plugin or what would be worse, it is in code directly, not encapsulated.
May i hear Your word about this?

EDIT: It seems that these reports are created by our programmers and copying jsp files should resolve this. Logic is also in jsp ( sql queries ). In this situation, my question is, how we can provide these views ( to which branch ) to the public?

**Comment by scrudden** [comment]
If I understand the question correctly the solution is for master and VIA branch to be merged. But in doing this we would need to test to make sure all functionality is still working correctly and there is no negative effect on the quality of predictions.

**Comment by changtung** [comment]
I saw that interesting report are in other version which in jsp files has
select statements but after merge it returns null in some type casting. Ill
update later and ill ty to provide third party code. Adding branch to my
github should be fine i guess.

21.07.2017 22:30 "Sean Óg Crudden" <notifications@github.com> napisał(a):

**Comment by changtung** [comment]
Can i help somehow with testing VIA to go to core ? What kind of tests that should be, how to move forward with this?

**Comment by scrudden** [comment]
Hi,

I have created a project to regression test the UI [here](https://github.com/scrudden/transitimeWebappRegression). It does not yet cover all reports or screens. You could add some tests to this which would be a great help.

Cheers,
Sean.

**Comment by scrudden** [comment]
@pacior Reports are in VIA branch now so can I close this?

**Comment by changtung** [comment]
Yes

12.12.2017 20:01 "Sean Óg Crudden" <notifications@github.com> napisał(a):
