### ISSUE TITLE
features to implement 

### ISSUE THREAD

**Issue by changtung** [TheTransitClock/transitime#75]
Hello, I wanted to describe proposition of a features that could be implemented.

1. In SheduleAdherenceByStop, there is a chart with late, early and on time vehicles. What if after clicking late vehicle, user could see vehicle id. I mean specific vehicle which drives and is late. 
2. In Schedule adherence map, there may be a box, label or small space, which presents vehicles with possible sorting by time early, late. 
From which branch currently is the best to fork, to implement these features? 

Best Regards, 
Grzegorz

**Comment by wkulesza** [comment]
I would comment on @pacior features.

ad 1. User would click on that bar and see which trip was affected by late/early arrival/departure time. Dispatcher than can see not only which driver was late but also which trip it was or which trips (if there were several records).

ad 2. I would see that placed in a sidebar on the right hand side of the screen.  Filtering and sorting features would assist dispachter in checking in real-time the situation and reacting straight away.

**Comment by scrudden** [comment]
I would suggest you branch from develop (branch name tc_issue_75) to make these changes.

**Comment by scrudden** [comment]
As this is two requirements perhaps it would be better to create a branch (and issue) for each feature.

**Comment by wkulesza** [comment]
@pacior created separate issues. this one can be closed
