### ISSUE TITLE
Clarifications about TripUpdate

### ISSUE THREAD

**Issue by wowkin2** [TheTransitClock/transitime#86]
Is tripUpdates showing `trip_update.stop_time_update.arrival.time` from the schedule if `schedule_relationship == "SCHEDULED"` or prediction is based on scheduled and VehiclePositions?

Found `trip_update.delay`, should I manually calculate `trip_update.stop_time_update.arrival.time + trip_update.delay` or is it already there?

**Comment by scrudden** [comment]
When schedule_relationship == "SCHEDULED" the arrival time is a predicted arrival time based on GPS data. The SCHEDULED means it knows which trip (or block) the vehicle is supposed to be running.

**Comment by wowkin2** [comment]
What about `trip_update.delay`?

**Comment by scrudden** [comment]
I am not 100% sure I understand your question. I think you are asking if the delay is already included in the arrival time. 

If so the answer is, yes. You do not need to add the two together.
