### ISSUE TITLE
Make TripUpdate.delay optional in GTFS Realtime trip updates feed

### ISSUE THREAD

**Issue by nselikoff** [TheTransitClock/transitime#92]
When using the GTFS realtime feeds generated by TheTransitClock for integration with Google Transit, we initially received Google's `INVALID_TRIP_UPDATE_DELAY_USAGE` warning, in the context of the GTFS Realtime trip updates feed. If both TripUpdate.delay and StopTimeUpdate arrival/departure times are specified, this warning from Google will occur, and they will drop the StopTimeUpdate predictions in favor of TripUpdate.delay. Since StopTimeUpdate predictions are higher fidelity (per stop basis not per trip basis), we commented out setting the TripUpdate.delay in our branch:

https://github.com/omnimodal/transitime/blob/2a4960dea4e062aeae87346a81617f19b5eefabf/transitclockApi/src/main/java/org/transitclock/api/gtfsRealtime/GtfsRtTripFeed.java#L157

However, other GTFS Realtime consumers may prefer having TripUpdate.delay available. Thoughts on how to make this optional/configurable @scrudden?

**Comment by scrudden** [comment]
Hi Nathan,

Would a BooleanConfigValue in the GtfsRtTripFeed class be a simple way of doing this? We could default it to not show delay based on the fact it is an optional/experimental field.

From the GTFS rt spec about delay

```
This field is still experimental, and subject to change. It may be formally adopted in the future.
```
Cheers,

Sean.

**Comment by nselikoff** [comment]
That sounds good @scrudden. Given that it's experimental I think it's fair to not show delay by default, though that could be a breaking change for anyone currently expecting that to be in TheTransitClock's GTFS Realtime Trip Updates feed.

**Comment by vsperez** [comment]
Hi Sean, Nathan.

Just to have it in mind. As far as I remember OBA uses the delay field.

Regards 
Vicente

**Comment by scrudden** [comment]
Hi,

This post on the OneBusAway developers list would indicate it is optional
for OneBusAway and that it will be calculated if it is not provided.

https://groups.google.com/d/msg/onebusaway-developers/bWvYOQXHj0s/aBPKy1NLAwAJ

Cheers,

Sean.

**Comment by vsperez** [comment]
Hi,
Completely right, my memory betrayed me a little (today finally I found the email) . “you'll need provide a TripUpdate feed, with each trip_update containing at least one stop_time_update with an arrival or departure delay or time.“
Regards, Vicente

**Comment by barbeau** [comment]
I agree that turning off TripUpdate.delay by default is the right approach.

**Comment by scrudden** [comment]
Done in this pull request #95
