### ISSUE TITLE
Synoptic view

### ISSUE THREAD

**Issue by vsperez** [TheTransitClock/transitime#98]
Hi,

I was thinking to add a feature to TheTransitClock that represents the route on a line. In this way, it is very easy to see where are the vehicles respect to each other or respect to the buses. 

One single line represents one direction, and the position of every single element (stop or vehicle) is proportionally placed over the line.

I've been already working a little over it.

**Comment by scrudden** [comment]
I have been using headway values while working on issue #74.

This uses the org.transitclock.core.headwaygenerator.LastArrivalsHeadwayGenerator to create the headway values with the headway then being updated in the vehicle state. This requires that the new caching mechanisms are running.

I am not sure if this headway information is passed to the API. There may be some of this worked on in #13.

**Comment by scrudden** [comment]
Merged #101
